@startuml use_case

left to right direction

actor "Player" as player
package BlackJack {
    usecase "hit/draw cards" as hit
    usecase "stand" as stand
    usecase "Split hand" as split
    usecase "Double the inlay" as double
    usecase "View your hand" as view_cards
}
actor "Dealer" as Dealer

player --> hit
player --> stand
player --> split
player --> double
player --> view_cards

hit <-- Dealer
stand <-- Dealer
split <-- Dealer
double <-- Dealer
view_cards <-- Dealer




@enduml